version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/CatalogService.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
